import type { LabelDefinitionMap } from '../types.js';

export const LABELS: LabelDefinitionMap = {
	'!hide': {
		id: '!hide',
		preferences: ['hide'],
		flags: ['no-override'],
		onwarn: 'blur',
		groupId: 'system',
		configurable: false,
	},
	'!no-promote': {
		id: '!no-promote',
		preferences: ['hide'],
		flags: [],
		onwarn: null,
		groupId: 'system',
		configurable: false,
	},
	'!warn': {
		id: '!warn',
		preferences: ['warn'],
		flags: [],
		onwarn: 'blur',
		groupId: 'system',
		configurable: false,
	},

	'dmca-violation': {
		id: 'dmca-violation',
		preferences: ['hide'],
		flags: ['no-override'],
		onwarn: 'blur',
		groupId: 'legal',
		configurable: false,
	},
	doxxing: {
		id: 'doxxing',
		preferences: ['hide'],
		flags: ['no-override'],
		onwarn: 'blur',
		groupId: 'legal',
		configurable: false,
	},

	porn: {
		id: 'porn',
		preferences: ['ignore', 'warn', 'hide'],
		flags: ['adult'],
		onwarn: 'blur-media',
		groupId: 'sexual',
		configurable: true,
	},
	sexual: {
		id: 'sexual',
		preferences: ['ignore', 'warn', 'hide'],
		flags: ['adult'],
		onwarn: 'blur-media',
		groupId: 'sexual',
		configurable: true,
	},
	nudity: {
		id: 'nudity',
		preferences: ['ignore', 'warn', 'hide'],
		flags: ['adult'],
		onwarn: 'blur-media',
		groupId: 'sexual',
		configurable: true,
	},

	nsfl: {
		id: 'nsfl',
		preferences: ['ignore', 'warn', 'hide'],
		flags: ['adult'],
		onwarn: 'blur-media',
		groupId: 'violence',
		configurable: true,
	},
	corpse: {
		id: 'corpse',
		preferences: ['ignore', 'warn', 'hide'],
		flags: ['adult'],
		onwarn: 'blur-media',
		groupId: 'violence',
		configurable: true,
	},
	gore: {
		id: 'gore',
		preferences: ['ignore', 'warn', 'hide'],
		flags: ['adult'],
		onwarn: 'blur-media',
		groupId: 'violence',
		configurable: true,
	},
	torture: {
		id: 'torture',
		preferences: ['ignore', 'warn', 'hide'],
		flags: ['adult'],
		onwarn: 'blur',
		groupId: 'violence',
		configurable: true,
	},
	'self-harm': {
		id: 'self-harm',
		preferences: ['ignore', 'warn', 'hide'],
		flags: ['adult'],
		onwarn: 'blur-media',
		groupId: 'violence',
		configurable: true,
	},

	'intolerant-race': {
		id: 'intolerant-race',
		preferences: ['ignore', 'warn', 'hide'],
		flags: [],
		onwarn: 'blur',
		groupId: 'intolerance',
		configurable: true,
	},
	'intolerant-gender': {
		id: 'intolerant-gender',
		preferences: ['ignore', 'warn', 'hide'],
		flags: [],
		onwarn: 'blur',
		groupId: 'intolerance',
		configurable: true,
	},
	'intolerant-sexual-orientation': {
		id: 'intolerant-sexual-orientation',
		preferences: ['ignore', 'warn', 'hide'],
		flags: [],
		onwarn: 'blur',
		groupId: 'intolerance',
		configurable: true,
	},
	'intolerant-religion': {
		id: 'intolerant-religion',
		preferences: ['ignore', 'warn', 'hide'],
		flags: [],
		onwarn: 'blur',
		groupId: 'intolerance',
		configurable: true,
	},
	intolerant: {
		id: 'intolerant',
		preferences: ['ignore', 'warn', 'hide'],
		flags: [],
		onwarn: 'blur',
		groupId: 'intolerance',
		configurable: true,
	},
	'icon-intolerant': {
		id: 'icon-intolerant',
		preferences: ['ignore', 'warn', 'hide'],
		flags: [],
		onwarn: 'blur-media',
		groupId: 'intolerance',
		configurable: true,
	},

	threat: {
		id: 'threat',
		preferences: ['ignore', 'warn', 'hide'],
		flags: [],
		onwarn: 'blur',
		groupId: 'rude',
		configurable: true,
	},

	spoiler: {
		id: 'spoiler',
		preferences: ['ignore', 'warn', 'hide'],
		flags: [],
		onwarn: 'blur',
		groupId: 'curation',
		configurable: true,
	},

	spam: {
		id: 'spam',
		preferences: ['ignore', 'warn', 'hide'],
		flags: [],
		onwarn: 'blur',
		groupId: 'spam',
		configurable: true,
	},

	'account-security': {
		id: 'account-security',
		preferences: ['ignore', 'warn', 'hide'],
		flags: [],
		onwarn: 'blur',
		groupId: 'misinfo',
		configurable: true,
	},
	'net-abuse': {
		id: 'net-abuse',
		preferences: ['ignore', 'warn', 'hide'],
		flags: [],
		onwarn: 'blur',
		groupId: 'misinfo',
		configurable: true,
	},
	impersonation: {
		id: 'impersonation',
		preferences: ['ignore', 'warn', 'hide'],
		flags: [],
		onwarn: 'alert',
		groupId: 'misinfo',
		configurable: true,
	},
	scam: {
		id: 'scam',
		preferences: ['ignore', 'warn', 'hide'],
		flags: [],
		onwarn: 'alert',
		groupId: 'misinfo',
		configurable: true,
	},
};
